apiVersion: v2
name: full-stack
description: Umbrella chart for Spark Job and API Service
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: spark-job
    version: 0.1.0
    tags:
      - install-spark
  - name: api-service
    version: 0.1.0
    tags:
      - install-service
