tags:
  install-spark: true
  install-service: true

# Global configurations sourced from deploy/charts/configs/
global:
  configMapNames:
    settings: "{{ .Release.Name }}-global-settings"
    appConfig: "{{ .Release.Name }}-app-config"

spark-job:
  spark:
    worker:
      replicas: 2

api-service:
  env:
    # Pointing to the spark master service within the same release
    sparkMasterUrl: "spark://{{ .Release.Name }}-spark-job-master:7077"
