apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-service.fullname" . }}-config
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
data:
  base-application.conf: |
{{ .Files.Get "configs/base-application.conf" | indent 4 }}
