image:
  repository: kudzai/test-service
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80

route:
  enabled: true
  host: ""
  tls:
    termination: edge

oauth:
  enabled: true
  clientId: "api-service-client"
  clientSecret: "secret"

env:
  sparkMasterUrl: "spark://spark-master:7077"

# External secret to load environment variables from (e.g. for application.conf)
envFromSecret: ""

extraEnv: {}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

ssl:
  enabled: true
  secretName: "my-cert-secret"
  keystoreFilename: "keystore.jks"
  truststoreFilename: "truststore.jks"
  # Keys in the secret containing the passwords
  keystorePasswordKey: "KEYSTORE_PASSWORD"
  truststorePasswordKey: "TRUSTSTORE_PASSWORD"
