apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spark-job.fullname" . }}-master
  labels:
    {{- include "spark-job.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "spark-job.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: master
  template:
    metadata:
      labels:
        {{- include "spark-job.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: master
    spec:
      containers:
        - name: spark-master
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPARK_MODE
              value: master
            - name: SPARK_PUBLIC_DNS
              value: {{ .Values.route.master.host | quote }}
            {{- include "spark-job.ssl.env" . | nindent 12 }}
            {{- include "spark-job.extraEnv" . | nindent 12 }}
          ports:
            - name: spark-master
              containerPort: {{ .Values.spark.master.port }}
            - name: web-ui
              containerPort: {{ .Values.spark.master.webUiPort }}
          resources:
            {{- toYaml .Values.spark.master.resources | nindent 12 }}
          volumeMounts:
            {{- include "spark-job.ssl.volumeMount" . | nindent 12 }}
            {{- include "spark-job.extraVolumeMounts" . | nindent 12 }}
      volumes:
        {{- include "spark-job.ssl.volume" . | nindent 8 }}
        {{- include "spark-job.extraVolumes" . | nindent 8 }}
