{{- if not .Values.global.externalConfigMaps.appConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configMapNames.appConfig }}
data:
  application.conf: |
{{ .Files.Get "configs/application.conf" | indent 4 }}
{{- end }}
