{{ if not .Values.global.externalConfigMaps.appConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.global.configMapNames.appConfig . | quote }}
data:
  application.conf: |
{{ .Files.Get "configs/application.conf" | indent 4 }}
{{ end }}
