{{ if not .Values.global.externalConfigMaps.settings }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.global.configMapNames.settings . | quote }}
data:
  global.conf: |
{{ .Files.Get "configs/global.conf" | indent 4 }}
{{ end }}
---
