base-stack:
  api-service:
    externalConfigMaps:
      settings: "{{ .Release.Name }}-domain-garage-global-settings"
      appConfig: "{{ .Release.Name }}-domain-garage-app-config"

config:
  environment: ""
  variant: ""
